spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paascloud_uac?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  application:
    name: nepous-provider-uac
  cloud:
    nacos:
      discovery:
        namespace: 4637c238-360c-4888-a9de-27dab15a89aa
        server-addr: localhost:8848
        group: test
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
    locator:
      discovery:
        enabled: true
  sleuth:
    enabled: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
nepous:
  security:
    oauth2:
      tokenStore: jwt
      clients[0]:
        clientId: nepous-provider-uac
        clientSecret: nepousUacSecrect
        scope: "*"
      clients[1]:
        clientId: nepous-provider-tpc
        clientSecret: nepousTpcSecrect
        scope: "*"
      client[2]:
        clientId: nepous-gateway
        clientSecret: nepousGateway
  oauth2:
    client:
      id: nepous-provider-uac
      accessTokenUrl: http://localhost:8888/uac/oauth/token
      clientId: nepous-provider-uac
      clientSecret: nepousUacSecrect
      clientAuthenticationScheme: header
#server:
#  servlet:
#    context-path: /uac
#logging:
#  level:
#    com.nepous.client.TestClient: debug
#
#    com.nepous.TpcFeignClientApi: debug
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always